### ISSUE TITLE
Ascribe Unit to declared defs without explicit return type

### ISSUE THREAD

**Issue by wiwa** [twitter/rsc#357]
```scala
trait T1 {
  def foo
}
```
Should be rewritten to
```scala
trait T1 {
  def foo: Unit
}
```

**Comment by ShaneDelmore** [comment]
This is already handled by the built in scalafix syntactic rule ProcedureSyntax. 
https://scalacenter.github.io/scalafix/docs/rules/ProcedureSyntax.html
