### ISSUE TITLE
Suppress @uncheckedVariance in type ascriptions

### ISSUE THREAD

**Issue by wiwa** [twitter/rsc#432]
RscCompat currently adds a ` @_root_.scala.annotation.unchecked.uncheckedVariance` annotation to some default parameter type ascriptions; we should get rid of these, esp. since type annotations have questionable support right now.

**Comment by ShaneDelmore** [comment]
Examples?  I see no instances of this in examples/ or scalafixTests/output/

**Comment by wiwa** [comment]
This only shows up with `better` flag off, so somewhat irrelevant now.

It can be reproduced with
```scala
def foo[K, V](
    x: Int,
    y: Map[K, V] = Map.empty[K,V]
  ): Int = 1
```
which becomes
```scala
def foo[K, V](
    x: Int,
    y: Map[K, V] = Map.empty[K,V]: _root_.scala.collection.immutable.Map[K, V] @_root_.scala.annotation.unchecked.uncheckedVariance
  ): Int = 1
```
