### ISSUE TITLE
Compare performance of Rsc and Kentucky Mule

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#9]
Kentucky Mule made quite a splash by announcing that [they are ~2000x faster than Scalac on some benchmarks](https://github.com/gkossakowski/kentuckymule). Rsc is [only ~20x faster than Scalac on some other benchmarks](../blob/master/docs/performance.md).

It would be great to investigate where this performance difference comes from:
  * From some flaws in the implementation of the typechecker?
  * From Rsc doing more work than Kentucky Mule (and Scalac doing even more work than Rsc)? 
  * From us not having spent time microoptimizing Rsc and instead pushing to have a first prototype as soon as possible (more on that decision in [our documentation](../blob/master/docs/compiler.md))?
  * From differences in benchmarks?

**Comment by theindigamer** [comment]
The link under "our documentation"
https://github.com/twitter/reasonable-scala/issues/docs/compiler.md 
seems dead. Maybe you want to link to 
https://github.com/twitter/reasonable-scala/blob/master/docs/compiler.md
instead?

**Comment by xeno-by** [comment]
@theindigamer Thank you for the bug report! Updated.

**Comment by theindigamer** [comment]
Sorry I didn't emphasize this earlier; the second link in the post is dead too. You can replace it with https://github.com/twitter/reasonable-scala/blob/master/docs/performance.md
